import { StyleSheet, Dimensions } from 'react-native';

const { width: screenWidth } = Dimensions.get('window');

export default StyleSheet.create({
    Safecontainer: {
        flex: 1,
        backgroundColor: '#fff',
    },
    container: {
        flex: 1,
        backgroundColor: '#fff',
        padding: 20,
    },
    contenedor: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingBottom: 10,
        marginBottom: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#D9D9D9',
    },
    desplegable: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingBottom: 10,
        marginBottom: 10,
    },
    contenedorConLinea: {
        paddingBottom: 10,
        marginBottom: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#D9D9D9',
    },
    titulo: {
        fontWeight: 'bold',
        fontSize: 20,
        color: 'grey',
        paddingVertical: 10,
    },
    informacion: {
        fontWeight: 'bold',
        fontSize: 18,
        color: '#FF893E',
        paddingVertical: 10,
    },
    informacionHTML: {
        fontSize: 18,
        color: 'grey',
        paddingVertical: 10,
        textAlign: 'justify',
        marginBottom: 10,
    },
    floatingButton: {
        width: 'auto',
        marginTop: 20,
        marginBottom: 40,
        padding: 20,
        borderRadius: 20,
        backgroundColor: '#00A8A2',
        justifyContent: 'center',
    },
    buttonText: {
        color: 'white',
        fontSize: 18,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    itemContainer: {
        marginBottom: 0,
        flexDirection: 'column',
    },
    itemFormatoOrdenes: {
        flexDirection: 'column',
        justifyContent: 'space-between',
        marginBottom: 25,
    },
    itemFormatoOrdenesTituloYAcepta: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginLeft: 0,
    },
    itemTitle: {
        fontWeight: 'bold',
        fontSize: 16,
        color: 'grey',
        marginBottom: 10,
    },
    itemText: {
        fontSize: 16,
        color: 'grey',
        marginBottom: 10,
    },
    itemObservaciones: {
        fontSize: 16,
        color: 'grey',
        marginBottom: 10,
        paddingRight: 10,
    },
    consultaNorma: {
        fontSize: 16,
        color: 'grey',
        marginBottom: 10,
        textAlign: 'center',
        padding: 10,
        borderWidth: 2,
        borderColor: '#0671B8',
        color: '#0671B8',
        fontWeight: 'bold',
        borderRadius: 20,
    },
    icon: {
        width: 25,
        height: 25,
    },
    descripcion: {
        padding: 20,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: '#0671B8',
        fontWeight: 'bold',
        fontSize: 16,
        color: '#0671B8',
        textAlign: 'center',
    },
    errorText: {
        fontSize: 18,
        color: 'red',
        textAlign: 'center',
        margin: 20,
        padding: 20,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: '#0671B8',
    },
    scrollContainer: {
        flexGrow: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    informacionTextoValidez: {
        fontSize: 16,
        color: 'grey',
        padding: 10,
        textAlign: 'center',
        marginBottom: 5,
        marginTop: 5,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: '#FF893E',
        width: screenWidth * 0.9,
    },
    fondoValidezOrden: {
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
    },
    apbHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 5,
    },
    iconContainer: {
        marginLeft: 10,
    },
    titulo: {
        fontWeight: 'bold',
        fontSize: 20,
        color: 'grey',
        paddingVertical: 10,
    },
    itemObservaciones: {
        fontSize: 18,
        textAlign: 'justify',
        color: 'grey',
        marginBottom: 10,
    },
    column: {
        flexDirection: 'column',
        marginBottom: 10,
    },
    rowAPB: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
});